# Generated by Django 5.0.6 on 2024-06-06 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
                ("end_year", models.IntegerField()),
                ("disable_override", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Paper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arxiv_id", models.TextField(unique=True)),
                ("title", models.TextField()),
                ("authors", models.TextField()),
                ("comment", models.TextField(blank=True, null=True)),
                ("journal_ref", models.TextField(blank=True, null=True)),
                ("pdf_link", models.TextField(unique=True)),
                ("page_link", models.TextField(unique=True)),
                ("withdrawn", models.BooleanField()),
                ("skip_download", models.BooleanField(default=False)),
                ("download_failed", models.BooleanField(default=False)),
                (
                    "download_attempt_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("categories", models.ManyToManyField(to="models.category")),
            ],
        ),
        migrations.CreateModel(
            name="MonthlyArchive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.TextField(max_length=4)),
                ("month", models.TextField(max_length=2)),
                ("total_entries", models.IntegerField()),
                ("scraped_entries", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="models.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExtraMetadata",
            fields=[
                (
                    "paper_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="models.paper",
                    ),
                ),
                ("summary", models.TextField()),
                ("doi", models.TextField(blank=True, null=True)),
                ("related_doi", models.TextField(blank=True, null=True)),
                ("report_no", models.TextField(blank=True, null=True)),
                ("published_date", models.DateTimeField()),
                ("updated_date", models.DateTimeField(blank=True, null=True)),
            ],
            bases=("models.paper",),
        ),
        migrations.AddField(
            model_name="paper",
            name="monthly_archive",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="models.monthlyarchive",
            ),
        ),
        migrations.CreateModel(
            name="PDF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_md5_hash",
                    models.TextField(max_length=32, unique=True),
                ),
                ("file_name", models.TextField(unique=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="models.paper",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TotalEntriesMismatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_entries", models.IntegerField()),
                ("counted_entries", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "monthly_archive",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="models.monthlyarchive",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="monthlyarchive",
            constraint=models.UniqueConstraint(
                fields=("category", "year", "month"),
                name="unique_monthly_archive_mismatch",
            ),
        ),
        migrations.AddConstraint(
            model_name="totalentriesmismatch",
            constraint=models.UniqueConstraint(
                fields=("monthly_archive", "total_entries", "counted_entries"),
                name="unique_total_entries_mismatch",
            ),
        ),
    ]
