# Generated by Django 5.0.6 on 2024-06-29 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("arxiv", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="archive",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.category"
            ),
        ),
        migrations.AddField(
            model_name="monthlyarchive",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.category"
            ),
        ),
        migrations.AddField(
            model_name="paper",
            name="categories",
            field=models.ManyToManyField(to="core.category"),
        ),
        migrations.AddField(
            model_name="paper",
            name="monthly_archive",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="arxiv.monthlyarchive"
            ),
        ),
        migrations.AddField(
            model_name="totalentriesmismatch",
            name="monthly_archive",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="arxiv.monthlyarchive"
            ),
        ),
        migrations.AddConstraint(
            model_name="monthlyarchive",
            constraint=models.UniqueConstraint(
                fields=("category", "year", "month"),
                name="unique_monthly_archive_mismatch",
            ),
        ),
        migrations.AddConstraint(
            model_name="totalentriesmismatch",
            constraint=models.UniqueConstraint(
                fields=("monthly_archive", "total_entries", "counted_entries"),
                name="unique_total_entries_mismatch",
            ),
        ),
    ]
